name: "Download Manager"
version: "2026.05.10"
image: "mazillka/ha-download-manager-addon"
description: "Download Manager"
slug: "ha-download-manager-addon"

arch:
  - amd64
  - aarch64

ingress: true
ingress_port: 3000

startup: services
boot: auto

panel_icon: mdi:download
host_network: false

map:
  - media:rw
  - data:rw
