name: "HA Download Manager"
slug: ha-download-manager
version: "1.0.43"
description: "Home Assistant Download Manager"

arch:
  - amd64
  - aarch64

ingress: true
ingress_port: 3000

startup: services
boot: auto

panel_icon: mdi:download
host_network: false

map:
  - media:rw
  - data:rw
